LIB =libsplit

include $(HOME)/etc/Makerules

$(LIBDIR)/$(LIB).a: \
	$(LIBDIR)/$(LIB).a(getselfcder.o) \
	$(LIBDIR)/$(LIB).a(getmulselfc.o) \
	$(LIBDIR)/$(LIB).a(readmoon.o) \
	$(LIBDIR)/$(LIB).a(initlin.o) \
	$(LIBDIR)/$(LIB).a(crlinsplit.o) \
	$(LIBDIR)/$(LIB).a(readsplit.o) \
	$(LIBDIR)/$(LIB).a(rspthead.o)

include	$(HOME)/etc/Makeranlib
