LIB =lib3d

include	$(HOME)/etc/Makerules

$(LIBDIR)/$(LIB).a: \
	$(LIBDIR)/$(LIB).a(getmulkern.o) \
	$(LIBDIR)/$(LIB).a(getkrhj.o) \
	$(LIBDIR)/$(LIB).a(getkernfls.o) \
	$(LIBDIR)/$(LIB).a(mksph2spemat.o) \
	$(LIBDIR)/$(LIB).a(rsph.o) \
	$(LIBDIR)/$(LIB).a(rspthead.o)

include	$(HOME)/etc/hjvh/Makeranlib
