include $(HOME)/etc/Makerules_sun

LIB =libtopo_sun

$(LIBDIR)/$(LIB).a: \
	$(LIBDIR)/$(LIB).a(getavetopo.o) \
	$(LIBDIR)/$(LIB).a(initetopo.o) \
	$(LIBDIR)/$(LIB).a(initcrust.o) \
	$(LIBDIR)/$(LIB).a(getavcrthck.o) \
	$(LIBDIR)/$(LIB).a(setupinterpcr5.o) \
	$(LIBDIR)/$(LIB).a(setupinterpcr2.o) \
	$(LIBDIR)/$(LIB).a(setupinterpcrff.o) \
	$(LIBDIR)/$(LIB).a(initmooncr.o) \
	$(LIBDIR)/$(LIB).a(interpttcr.o)

include	$(HOME)/etc/Makeranlib
