include $(HOME)/etc/Makerules_sun

LIB =libutil_sun

$(LIBDIR)/$(LIB).a: \
	$(LIBDIR)/$(LIB).a(int2char.o) \
	$(LIBDIR)/$(LIB).a(strgrep.o) \
	$(LIBDIR)/$(LIB).a(strgrepdelim.o) \
	$(LIBDIR)/$(LIB).a(wsphhead.o) \
	$(LIBDIR)/$(LIB).a(getfdp.o) \
	$(LIBDIR)/$(LIB).a(istlen.o) \
	$(LIBDIR)/$(LIB).a(rsphhead.o) \
	$(LIBDIR)/$(LIB).a(wint2ch.o)

	ranlib $(LIBDIR)/$(LIB).a
