include $(HOME)/etc/Makerules_sun
LIBDIR = ..

$(LIBDIR)/libSphFunc_sun.a: \
	$(LIBDIR)/libSphFunc_sun.a(legndr.o) \
	$(LIBDIR)/libSphFunc_sun.a(normylm.o) \
	$(LIBDIR)/libSphFunc_sun.a(ylm.o) \
	$(LIBDIR)/libSphFunc_sun.a(ylm02xlm.o)
	ranlib $(LIBDIR)/libSphFunc_sun.a
