c::::::::::::::
c	daymo.f77
c::::::::::::::
CPROG DAYMO
CXREF
      INTEGER FUNCTION DAYMO (DOFY,MONTH,DAY,YEAR)
C
C FUNCTION DAYMO DETERMINES THE MONTH AND DAY
C OF THE MONTH,GIVEN THE YEAR AND DAY OF YEAR.
C IT RETURNS 1 IF IT WAS SUCCESSFUL,0 OTHERWISE.
C IF DOFY IS NOT WITHIN LEGAL LIMITS,MONTH AND
C DAY WILL BE RETURNED AS ZERO.
C
C
C CALLS:
C   LPYR
C
C      PROGRAMMED BY MADELEINE ZIRBES
C         SEPTEMBER 15,1980
C
C DAY OF YEAR - INPUT
      INTEGER DOFY
C MONTH - OUTPUT
      INTEGER MONTH
C DAY OF MONTH - OUTPUT
      INTEGER DAY
C YEAR - INPUT
      INTEGER YEAR
C
C DAY OF YEAR
      INTEGER IDAY
C FUNCTION
      INTEGER LPYR
C NUMBER OF DAYS IN MONTH
      INTEGER MDAYS(12)
      DATA MDAYS/31,28,31,30,31,30,31,31,30,31,30,31/
C
      IDAY = DOFY
      IF(.NOT.(IDAY.LT.1))GOTO 23000
         MONTH = 0
         DAY = 0
         DAYMO = (0)
         RETURN
C
23000 CONTINUE
      IF(.NOT.(LPYR(YEAR).EQ.1))GOTO 23002
         MDAYS(2) = 29
         GOTO 23003
C     ELSE
23002    CONTINUE
         MDAYS(2) = 28
23003 CONTINUE
C
      DO 23004 MONTH = 1,12
         DAY = IDAY
         IDAY = IDAY - MDAYS(MONTH)
         IF(.NOT.(IDAY.LE.0))GOTO 23006
            DAYMO = (1)
            RETURN
23006    CONTINUE
23004    CONTINUE
C
      MONTH = 0
      DAY = 0
      DAYMO = (0)
      RETURN
C
      END
