c::::::::::::::
c	doy.f77
c::::::::::::::
CPROG DOY
CXREF
      INTEGER FUNCTION DOY (MONTH,DAY,YEAR)
C
C FUNCTION DOY DETERMINES THE DAY OF THE
C YEAR,GIVEN THE MONTH,DA AD YEAR.
C IF MONTH OR DAY ARE ILLEGAL,THE RETURN
C VALUE OF THE FUNCTION IS ZERO.
C
C
C CALLS:
C   LPYR
C
C      PROGRAMMED BY MADELEINE ZIRBES
C         SEPTEMBER 15,1980
C
C MONTH - INPUT
      INTEGER MONTH
C DAY OF MONTH - INPUT
      INTEGER DAY
C YEAR - INPUT
      INTEGER YEAR
C FUNCTION
      INTEGER LPYR
      INTEGER INC
      INTEGER NDAYS(12)
      DATA NDAYS /0,31,59,90,120,151,181,212,243,273,304,334/
C
      IF(.NOT.(MONTH .LT.1 .OR. MONTH .GT. 12))GOTO 23000
         DOY = (0)
         RETURN
23000 CONTINUE
      IF(.NOT.(DAY .LT. 1 .OR. DAY .GT. 31))GOTO 23002
         DOY = (0)
         RETURN
23002 CONTINUE
      IF(.NOT.(LPYR(YEAR).EQ.1 .AND. MONTH .GT. 2))GOTO 23004
         INC = 1
         GOTO 23005
C     ELSE
23004    CONTINUE
         INC = 0
23005 CONTINUE
      DOY = (NDAYS(MONTH) + DAY + INC)
      RETURN
      END
