include $(HOME)/etc/Makerules_sun

LIB =librot_sun
LIBDIR =  ..

$(LIBDIR)/$(LIB).a: \
	$(LIBDIR)/$(LIB).a(legndr.o) \
	$(LIBDIR)/$(LIB).a(piylms.o) \
	$(LIBDIR)/$(LIB).a(rotmx2.o) \
	$(LIBDIR)/$(LIB).a(rotvc1t.o) \
	$(LIBDIR)/$(LIB).a(rotvcyt.o) \
	$(LIBDIR)/$(LIB).a(rotvcz.o) \
	$(LIBDIR)/$(LIB).a(ylm.o) \
	$(LIBDIR)/$(LIB).a(ylmray.o) 

include	$(HOME)/etc/Makeranlib
