
      parameter (LPNMPH=0)
      parameter (LPLNMP=8)
      parameter (LPNDEP=LPNMPH+LPLNMP)
      parameter (LPADP0=LPNDEP+1)
      parameter (LPLNPR=LPADP0+1)
      parameter (LPLNHD=LPLNPR+1)
        parameter (LPDEPT=0)
        parameter (LPADDP=LPDEPT+1)
        parameter (LPNDEL=LPADDP+1)
        parameter (LPADSP=LPNDEL+1)
        parameter (LPDMIN=LPADSP+1)
        parameter (LPDMAX=LPDMIN+1)
        parameter (LPLNH1=LPDMAX+1)
