LIB = libseig
LIBDIR = ..

include $(HOME)/etc/Makerules

$(LIBDIR)/$(LIB).a: \
	$(LIBDIR)/$(LIB).a(setupb.o) \
	$(LIBDIR)/$(LIB).a(bpsplq.o) \
	$(LIBDIR)/$(LIB).a(bpsplhrho.o) \
	$(LIBDIR)/$(LIB).a(bpsplh5.o) \
	$(LIBDIR)/$(LIB).a(bpsplk5.o) \
	$(LIBDIR)/$(LIB).a(bpspln5.o) \
	$(LIBDIR)/$(LIB).a(bpumlmchb.o) \
	$(LIBDIR)/$(LIB).a(bpumlmpp5.o) \
	$(LIBDIR)/$(LIB).a(bpumlm47.o) \
	$(LIBDIR)/$(LIB).a(bpumlm.o) \
	$(LIBDIR)/$(LIB).a(corfac.o) \
	$(LIBDIR)/$(LIB).a(mdpars.o) \
	$(LIBDIR)/$(LIB).a(mdparsic.o) \
	$(LIBDIR)/$(LIB).a(mdprt.o) \
	$(LIBDIR)/$(LIB).a(pumlm.o) \
	$(LIBDIR)/$(LIB).a(fetch.o) \
	$(LIBDIR)/$(LIB).a(seteig.o) \
	$(LIBDIR)/$(LIB).a(setup.o) \
	$(LIBDIR)/$(LIB).a(spread.o) \
	$(LIBDIR)/$(LIB).a(setkr.o) \
	$(LIBDIR)/$(LIB).a(openkr.o) \
	$(LIBDIR)/$(LIB).a(getkr.o)


include	$(HOME)/etc/Makeranlib
