
C**********************************************************************
      SUBROUTINE EPCNTR(EPLAT,EPLON)
      save
      DATA RAD,GEOCO,TWOPI/0.0174533,0.993277,6.2831853072/
      EPL=ATAN(GEOCO*TAN(EPLAT*RAD))
      AE=SIN(EPL)
      BE=COS(EPL)
      EPO=EPLON*RAD
      CE=COS(EPO)
      DE=SIN(EPO)
      RETURN
      ENTRY ANGLES(STLAT,STLON,DELTA,AZEP,AZST,THETA,PHI,PSI,AZ12)
      SLA=ATAN(GEOCO*TAN(STLAT*RAD))
      AS=SIN(SLA)
      BS=COS(SLA)
      SLO=STLON*RAD
      CS=COS(SLO)
      DS=SIN(SLO)
      CDIF=CE*CS+DE*DS
      CDEL=AE*AS+BE*BS*CDIF
      DELTA=ACOS(CDEL)
      SDIF=DS*CE-CS*DE
      SDEL=SIN(DELTA)
      CAZE=(AS-AE*CDEL)/(BE*SDEL)
      SAZE=SDIF*BS/SDEL
      AZEP=ATAN2(SAZE,CAZE)
      IF(AZEP.LT.0.) AZEP=AZEP+TWOPI
      AZST=-ATAN2(BE*SDIF,(AE-AS*CDEL)/BS)
      IF(AZST.LT.0.) AZST=AZST+TWOPI
      COST=BE*SAZE
      THETA=ACOS(COST)
      SINT=SIN(THETA)
      PHI=ATAN2(-CAZE,-AE*COST/BE)+EPO
      PHI=AMOD(PHI,TWOPI)
      IF(PHI.LT.0.) PHI=PHI+TWOPI
      PSI=-ATAN2(-CAZE*BS,-AS)
      IF(PSI.LT.0.) PSI=PSI+TWOPI
      AZ1=ATAN2(-BE*SIN(PHI-EPO),AE/SINT)
      AZ2=ATAN2(-BS*SIN(PHI-SLO),AS/SINT)
      AZ12=AMOD(AZ1+AZ2,TWOPI)
      IF(AZ12.LT.0.) AZ12=AZ12+TWOPI
      RETURN
      END
