
C$**********************************************************************
      SUBROUTINE GETMDL(LUHMDL,NHTMDL,IFCCN,KFIL,KFILAN)
      save
      CHARACTER*1 NHTMDL(12)
      CHARACTER*12 HETMDL
      INTEGER*4 IHTMDL(3)
      DIMENSION KFIL(4),KFILAN(4)
      COMMON/SCAN/ PATH(204)
     1  ,IHTMDL,IFANI,LMAXM,LENY,NPMM,PERTM(588),IFCC,MFIL(4),MFILAN(4)
      DATA MAXLEN/588/
      IFCC=IFCCN
      DO 80 I=1,4
      MFIL(I)=KFIL(I)
   80 MFILAN(I)=KFILAN(I)
      IF(NHTMDL(1).NE.' ') GOTO 90
      HETMDL='            '
      READ(HETMDL,111) IHTMDL
  111 FORMAT(3A4)
      IFANI=0
      LMAXM=0
      LENY=0
      NPMM=0
      DO 92 I=1,MAXLEN
   92 PERTM(I)=0.
      RETURN
C
   90 WRITE(HETMDL,97) (NHTMDL(I),I=1,12)
   97 FORMAT(12A1)
      READ(HETMDL,111) IHTMDL
      CLOSE(UNIT=LUHMDL)
c     OPEN(UNIT=LUHMDL,FILE=HETMDL,STATUS='OLD',FORM='FORMATTED'
c    1  ,RECFM='DATASENSITIVE',IOINTENT='INPUT',PAD='YES')
      open(luhmdl,file=hetmdl,status='old')
      READ(LUHMDL,702) IFANI,IFMINO,LMAXM
  702 FORMAT(3I5)
      LMAXM1=LMAXM+1
      LENY=LMAXM1**2
      NPMM=12+(IFANI-1)*5
      DO 703 IP=1,NPMM
      IND=1+(IP-1)*LENY
      DO 704 L1=1,LMAXM1
      IND1=IND+2*(L1-1)
      IF(IND1.GT.MAXLEN) STOP 'MODEL HAS TOO MANY PARAMETERS'
      READ(LUHMDL,705) (PERTM(I),I=IND,IND1)
  705 FORMAT(11E12.5)
  704 IND=IND1+1
  703 CONTINUE
      CLOSE(UNIT=LUHMDL)
      RETURN
      END
