
C$**********************************************************************
CPROG SOURPA
CXREF
      SUBROUTINE SOURPA(F,SCMOM,PHS,DEL,RLAM,EIVALS,PLUNGS,AZIMS,
     1EIVECS)
      save
      DIMENSION F(6),PHS(2),DEL(2),RLAM(2),EIVALS(3),EIVECS(3,3),
     1PLUNGS(3),AZIMS(3)
      CALL EQPAR(F,SCMOM,PHS,DEL,RLAM,EIVALS,EIVECS,PLUNGS,AZIMS)
      DO 1 I=1,3
      E=EIVALS(I)*1.E30
      WRITE(6,1000) I,E,PLUNGS(I),AZIMS(I)
    1 WRITE(16,1000) I,E,PLUNGS(I),AZIMS(I)
 1000 FORMAT(3X,'EIGENVALUE ',I1,' = ',E13.6,' PLUNGE =',F6.2,
     1' AZIMUTH =',F7.2)
      SC=SCMOM*1.E30
      WRITE(6,1001) SC
      WRITE(16,1001) SC
 1001 FORMAT('   BEST DOUBLE COUPLE; SCALAR MOMENT = ',E13.6)
      DO 2 I=1,2
      WRITE(6,1002) I,PHS(I),DEL(I),RLAM(I)
      WRITE(16,1002) I,PHS(I),DEL(I),RLAM(I)
    2 CONTINUE
 1002 FORMAT(3X,'FAULT PLANE ',I1,' STRIKE =',F7.2,' DIP =',
     1F6.2,' SLIP =',F8.2)
c	,' ** NORMAL FAULT: SLIP = -90 DEG **'
      RETURN
      END
