
C$**********************************************************************
      SUBROUTINE STRNSF
      save
      COMMON/INTAP/ IDUM1(3),IFACT,ITER,JK,IT1,IT2,INSTR,NTRANS,I1S,
     1I1F,I2S,I2F,IDUM3(2)
      COMPLEX BRESP,RESP,CSYNT,CSEI
      DIMENSION CSYNT(257),CSEI(257)
      COMMON/AP1/ DUM1(14),F(6),DUM2(2),R0,DOM,DTORG,DURTN
      COMMON/IAP5/ SYNT(5140),ADD5(7710)
      COMMON/IAP6/ BRESP(257,5)
      COMMON/IAP3/ TRACE(514),F31(514)
      COMMON/AP2/ SSEI(514),RESP(257),F32(7712)
      EQUIVALENCE (CSYNT(1),TRACE(1)),(CSEI(1),SSEI(1))
      NPTC=2**NTRANS+1
      DO 5 I=1,NPTC
      OM=DOM*FLOAT(I-1)
      ARG=OM*DURTN
      FACT=1.
      IF(ARG.NE.0.) FACT=SIN(ARG)/ARG
      ARG=-OM*DTORG
      CA=COS(ARG)*FACT
      SA=SIN(ARG)*FACT
    5 RESP(I)=BRESP(I,INSTR)*CMPLX(CA,SA)
      N=1
   10 IND=(N-1)*514-I1S+1
      CALL FVCLR(TRACE,1,514)
      DO 1 I=I1S,I2S
    1 TRACE(I)=SYNT(IND+I)
      CALL RFOUR(TRACE,NTRANS,1)
      DO 2 I=1,NPTC
      FACT=1.
      IF(N.GT.6) FACT=1./R0
    2 CSYNT(I)=CSYNT(I)*RESP(I)*CMPLX(FACT,0.)
      IND=(N-1)*514+1
      CALL STAPCL(TRACE,SYNT(IND),I1F,I2F,IT1,IT2)
      N=N+1
      IF(N.LE.IFACT) GO TO 10
      IF(ITER.LE.0) RETURN
      CALL FVCLR(SSEI,1,514)
      NPTR=2*NPTC
      N=1
   21 I=(N-1)*514+1
cC      CALL FVSMA2(SYNT(I),1,F(N),SSEI,1,NPTR)
      call saxpy(NPTR,F(N),SYNT(I),1,SSEI,1)
      N=N+1
      IF(N.LE.6) GO TO 21
      DO 22 I=1,NPTC
      OM=FLOAT(I-1)*DOM
      CSYNT(I)=CSEI(I)*CMPLX(0.,-OM)
   22 CONTINUE
      CALL FVMOV(TRACE,1,SYNT(4627),1,514)
      RETURN
      END
